### ISSUE TITLE
ValueError: can't extend empty axis 0 using modes other than 'constant' or 'empty'

### ISSUE THREAD

**Issue by i-02** [craigfrancis/audio-detect#9]
First of all, thanks so much for making this project! I searched for a long time for something like this before finding your code.

However, I keep getting the following error when running `python3 ./process.py ./example/config.py ./example/source.mp3;` (Full output reproduced for context):

```
Config
  Hz Min Score: 0.15
Load Source
  ./example/source.mp3 (6322.155102040816 & 22050)
Load Samples
Traceback (most recent call last):
  File "./process.py", line 89, in <module>
    sample_frames, fft_window, n_columns = stft_raw(sample_series, sample_rate, win_length, hop_length, hz_count, dtype)
  File "<string>", line 73, in stft_raw
  File "<__array_function__ internals>", line 5, in pad
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/lib/arraypad.py", line 814, in pad
    raise ValueError(
ValueError: can't extend empty axis 0 using modes other than 'constant' or 'empty'
```

I'm on macOS using Terminal. I even tried running it with your example files, and I still got the exact same error. Any idea what might be causing this?

**Comment by craigfrancis** [comment]
Hi, sorry I've not been able to look at this issue for the last couple of days.

Have you been able to work out what's happening?

At a guess, I think you might not have `ffmpeg` installed - for ease, I usually install this program via [Homebrew](https://brew.sh/) when I'm using MacOS.

---

Initial thoughts...

There is a problem in `stft_raw()`.

That function takes the output from the `pcm_data()` function (which gets the output from `ffmpeg`).

We should be getting an array of 32 bit floats, representing the audio file... `stft_raw()` gets this array via the variable `series`.

If I'm reading the error you've shown correctly, it has a problem on line 73 in `process.source.py`:

    series = np.pad(series, int(n_fft // 2), mode=pad_mode)

Specifically [Line 816](https://github.com/numpy/numpy/blob/516355fc0cd4f507075abb9df5442ce8a58e6ab3/numpy/lib/arraypad.py#L814) in the `pad()` function provided by the `numpy` library.

Note how that `ValueError` only happens if the `array.size == 0`, which implies the `series` array is empty?

---

As an aside, I've just added a `size` check to the output from `ffmpeg`, so that will hopefully show a more useful error in future.

**Comment by i-02** [comment]
No worries, I didn't get a chance to work on it any more myself until today. Thanks for your response. I did already have `ffmpeg` installed, so I'm really not sure what the issue was. It was most likely just some simple mistake I was making, because a clean reinstall of your code caused the issue to disappear (at least when testing with your sample files). However, after generating my sample from my source file, I'm now getting the following error when I attempt to run `python3 ./process.py ./example/config.py ./example/source.mp3;`

```
Config
  Hz Min Score: 0.15
Load Source
  ./example/source.mp3 (6322.155102040816 & 22050)
Load Samples
  Missing data from Audio file "./example/samples/.DS_Store" via "ffmpeg".
```

I showed hidden files but there is no `.DS_Store` file in the directory. Any idea what's going on now, or if this is even related? I can open it as a separate issue if necessary.

**Comment by craigfrancis** [comment]
I've just updated the "process.py" script ([line 78](https://github.com/craigfrancis/audio-detect/commit/b45424a00ab018049f29097fd38e108c3d75d49d)) so that it will ignore hidden files.

When it comes to MacOS, the `. DS_Store` files are created at all kinds of random times... I suspect you checked the contents of that folder with Finder, then when you switched focus back to the Terminal, that file was created (that file kinda records details about how you looked at the folder in Finder, e.g. icon size and layout).

**Comment by i-02** [comment]
That makes sense; and yeah that is exactly what I did. Thanks so much for helping with this, and thanks again for creating the tool in the first place! It's working perfectly for me now, so I'll close the issue.

**Comment by craigfrancis** [comment]
np, and hope it works for your project.
